[package]
name = "cranpose-runtime-std"
version.workspace = true
edition.workspace = true
description = "Standard library backed runtime services for Cranpose"
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
cranpose-core = { workspace = true }
